import type { AgentDefinition } from '../types'

export const rootAgent: AgentDefinition = {
  id: 'root',
  displayName: 'RavenClaw',
  toolNames: [
    'Read',
    'Grep',
    'Glob',
    'ListDir',
    'ReadSubtree',
    'Edit',
    'Write',
    'ApplyPatch',
    'NotebookEdit',
    'Bash',
    'Skill',
    'Fetch',
    'WebSearch',
    'TodoWrite',
    'TaskOutput',
    'TaskStop',
    'AskUser',
    'SetOutput',
    'AddDir',
    'ToolSearch',
    'ToolCall',
    'LSP',
    'EnterWorktree',
    'ExitWorktree',
    'CronCreate',
    'CronList',
    'CronDelete',
    'CronSetEnabled',
    'Agent',
    'EnterPlanMode',
    'ExitPlanMode',
  ],
  spawnableAgents: ['general', 'file-finder', 'command-runner', 'reviewer', 'researcher-web'],
  inheritParentSystemPrompt: false,
  includeMessageHistory: false,
  maxRounds: 80,
  outputMode: 'last_message',
}
